name: timing_flutter
description: Learn to identify sub-second timing intervals.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+100

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.5.4

  url_launcher: ^6.1.7
  stow_plain: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  icons_launcher: ^3.0.3

  golden_screenshot: ^10.0.0

flutter:
  uses-material-design: true

# ./scripts/generate_icons.sh
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#1e2227"
      adaptive_foreground_image: "assets/icon/icon_android_foreground.png"
      adaptive_monochrome_image: "assets/icon/icon_android_monochrome.png"
    ios:
      enable: true
      image_path: "assets/icon/icon_ios.png"
    macos:
      enable: false
      image_path: "assets/icon/icon_ios.png"
    windows:
      enable: false
    linux:
      enable: false
    web:
      enable: true
