name: timing_flutter
description: Learn to identify sub-second timing intervals.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.15+15

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.5.4

  url_launcher: ^6.1.7
  stow_plain: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  icons_launcher: ^3.0.3

  golden_screenshot: ^8.1.0

flutter:
  uses-material-design: true

# dart run icons_launcher:create
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/icon/icon_foreground.png"
    ios:
      enable: true
      image_path: "assets/icon/icon_maskable.png"
    macos:
      enable: false
      image_path: "assets/icon/icon_maskable.png"
    windows:
      enable: false
    linux:
      enable: false
    web:
      enable: true
