name: Build for Android

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .dart_tool/
            build/
            linux/flutter/ephemeral/
            macos/Flutter/ephemeral/
            windows/flutter/ephemeral/
            .flutter-plugins-dependencies
            pubspec.lock
          key: ${{ runner.OS }}-TimingTrainer-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/*.dart') }}
          restore-keys: |
            ${{ runner.OS }}-TimingTrainer-

      - name: Remove dev dependencies
        run: ./patches/remove_dev_dependencies.sh

      - name: Setup keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > android/keystore.jks
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../keystore.jks" >> android/key.properties

      - name: Setup Flutter
        uses: adil192/setup-flutter-submodule@v1
        with:
          flutter-path: submodules/flutter

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'

      - run: flutter pub get

      - name: Build apk
        run: flutter build apk --no-pub
      - name: Build aab
        run: flutter build appbundle --no-pub

      - name: Rename apk and aab
        id: rename
        run: |
          buildName=$(grep "version: " pubspec.yaml | sed 's/version: //g' | sed 's/+.*//g')
          apkName="TimingTrainer_v${buildName}.apk"
          echo "apkName=$apkName" >> $GITHUB_OUTPUT
          aabName="TimingTrainer_v${buildName}.aab"
          echo "aabName=$aabName" >> $GITHUB_OUTPUT

          mkdir -p output
          mv build/app/outputs/flutter-apk/app-release.apk output/$apkName
          mv build/app/outputs/bundle/release/app-release.aab output/$aabName

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: TimingFlutter-Android-Apk
          path: output/${{ steps.rename.outputs.apkName }}
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: TimingFlutter-Android-Aab
          path: output/${{ steps.rename.outputs.aabName }}

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: output/TimingTrainer_v*
